#%RAML 1.0
title: Mountains
version: v1
description: Basic web service for my Microservice template project.
mediaType: [ application/json ]

types: 
  mountain: !include types/mountain.raml

resourceTypes: 
  collection: !include resourceTypes/collection.raml
  item: !include resourceTypes/item.raml

/mountains:
  type: { collection: { typeName: mountain } }
  /{id}:
    type: { item: { typeName: mountain } }