#%RAML 1.0 ResourceType
usage: This resourceType should be used for any collection of items
description: The collection of <<resourcePathName>>
get:
  description: Get all <<resourcePathName>>, optionally filtered
  responses: 
    200:
      body: 
        type: <<typeName>>[]
    403:
      description: You don't have permission to access this recource.
   
post:
  description: Create a new <<resourcePathName | !singularize>>
  body: 
    type: <<typeName>>
  responses: 
    201:
      description: <<typeName>> created in collection.
    403:
      description: You don't have permission to access this recource.