#%RAML 1.0 ResourceType
usage: Base type for all objects
description: Base type for all objects with the basic descriptions.

get:
  description: Get the <<resourcePathName>>
  responses: 
    200:
      body: 
        type: <<item>>
put:
post:
patch:
delete: